image: maven:3.3.3-jdk-8

script:
  - mvn clean
  - mvn install
  
pubish:
  docker:
    username: myuser
    password: mypassword
    email: foobar@mail.com
    repo: foo/bar
    tag: latest
    file: Dockerfile
