# Database settings.
database:

# access by docker
# docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
# docker run -it --link postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres'
  driverClass: org.postgresql.Driver
  user: postgres
  password: mysecretpassword
  url: jdbc:postgresql://localhost:5432/dropangular


logging:
  level: INFO

  loggers:
    me.pedrazas.dropangular: DEBUG

  appenders:
    - type: file
      currentLogFilename: /var/log/dropangular/dropangular.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/dropangular/dropangular-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC

    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
